workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 20
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
