workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 20
    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
    scripts:
      - name: Build iOS IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_ID